version: 2.1

jobs:
  build:
    working_directory: ~/mynachain
    docker:
      - image: yukijs/mynachain:latest
    steps:
      - checkout
      - restore_cache:
          key: registry-cache-{{ checksum 'Cargo.lock'}}
      - restore_cache:
          key: index-cache-{{ checksum 'Cargo.lock'}}
      - restore_cache:
          key: build-cache-{{ checksum 'Cargo.lock'}}
      - run:
          name: "Build"
          command: "cargo build --release"
          no_output_timeout: 1h
      - save_cache:
          key: build-cache-{{ checksum 'Cargo.lock'}}
          paths: ./target
      - save_cache:
          key: index-cache-{{ checksum 'Cargo.lock'}}
          paths: ~/.cargo/git
      - save_cache:
          key: build-cache-{{ checksum 'Cargo.lock'}}
          paths: ~/.cargo/registry
      - save_cache:
          key: repo-cache-{{ .Environment.CIRCLE_SHA1 }}
          paths: ./
      - store_artifacts:
          path: target/release/node-template
          prefix: binary
  test:
    working_directory: ~/mynachain
    docker:
      - image: circleci/rust:latest
    steps:
      - restore_cache:
          key: repo-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: "unit test"
          command: cargo test --release

workflow:
  version: 2
  build:
    jobs:
      - build
      - test:
        requires:
          - build
      